[build]
  command = "eleventy"
  publish = "_site"
  functions = "_site/functions"  

[dev]
  publish = "_site"
  functions = "_site/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"  

[template.environment]
  STRIPE_PUBLISHABLE_KEY = "Add your Stripe publishable key here: pk_test_xxx"
  STRIPE_SECRET_KEY = "Add your Stripe secret key here: sk_test_xxx"
  STRIPE_WEBHOOK_SECRET = "[Optional] Add your webhook secret here: whsec_xxx"
